/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_api_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trace */
        post: operations["trace_api_trace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_datasets__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diff */
        post: operations["diff_api_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Traces */
        get: operations["traces_api_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stored Trace */
        get: operations["stored_trace_api_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_dataset_api_datasets_post */
        Body_upload_dataset_api_datasets_post: {
            /** File */
            file: string;
            /** Name */
            name?: string | null;
        };
        /** Check */
        Check: {
            /** Node Id */
            node_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "merge_validate" | "row_count" | "not_null" | "not_empty" | "dtype" | "schema" | "pandera";
            /** Line */
            line?: number | null;
            /**
             * Position
             * @enum {string}
             */
            position: "before" | "after" | "replace";
            /** Code */
            code: string;
            /** Passes */
            passes: boolean;
            /** Reason */
            reason: string;
        };
        /** ColumnDiff */
        ColumnDiff: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "added" | "removed" | "renamed" | "changed" | "same";
            /** Renamed From */
            renamed_from?: string | null;
            /** Dtype A */
            dtype_a?: string | null;
            /** Dtype B */
            dtype_b?: string | null;
            /** Nulls A */
            nulls_a?: number | null;
            /** Nulls B */
            nulls_b?: number | null;
            /** Unique A */
            unique_a?: number | null;
            /** Unique B */
            unique_b?: number | null;
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Name */
            name: string;
            /** Dtype */
            dtype: string;
            /** Null Count */
            null_count: number;
            /** N Unique */
            n_unique?: number | null;
        };
        /** DatasetInfo */
        DatasetInfo: {
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /**
             * Format
             * @enum {string}
             */
            format: "csv" | "tsv" | "parquet" | "json" | "jsonl";
            /** Size Bytes */
            size_bytes: number;
            /** Rows */
            rows: number;
            /** Cols */
            cols: number;
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
            /** Uploaded At */
            uploaded_at: string;
        };
        /** DiffRequest */
        DiffRequest: {
            trace: components["schemas"]["TraceResult"];
            /** A */
            a: string;
            /** B */
            b: string;
        };
        /** Edge */
        Edge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Role
             * @default input
             * @enum {string}
             */
            role: "input" | "left" | "right" | "other";
        };
        /** Example */
        Example: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Code */
            code: string;
        };
        /** Finding */
        Finding: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "row_loss" | "row_explosion" | "null_origin" | "dtype_drift" | "join";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Node Id */
            node_id: string;
            /** Message */
            message: string;
            /** Column */
            column?: string | null;
            /** Example Kind */
            example_kind?: ("dropped" | "unmatched_left" | "unmatched_right" | "duplicate_keys_left" | "duplicate_keys_right" | "null_keys_left" | "null_keys_right" | "nulls") | null;
        };
        /** FrameProfile */
        FrameProfile: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "DataFrame" | "Series";
            /** Rows */
            rows: number;
            /** Cols */
            cols: number;
            /** Memory Bytes */
            memory_bytes: number;
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
            /** Index */
            index: string[];
            /** Sample Columns */
            sample_columns: string[];
            /** Sample */
            sample: unknown[][];
            /** Sample Index */
            sample_index: unknown[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Hint
         * @description An optimization that keeps the result the same (pushdowns, anti-patterns).
         */
        Hint: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "filter_before_join" | "filter_earlier" | "unused_columns" | "useless_sort" | "row_apply" | "duplicate_read" | "inplace";
            /** Node Id */
            node_id: string;
            /** Message */
            message: string;
            /** Suggestion */
            suggestion?: string | null;
            /** Related */
            related?: string[];
        };
        /** Node */
        Node: {
            /** Id */
            id: string;
            /** Op */
            op: string;
            /**
             * Category
             * @enum {string}
             */
            category: "source" | "filter" | "projection" | "join" | "aggregate" | "sort" | "limit" | "reshape" | "mutate" | "other";
            /** Label */
            label: string;
            /** Var Name */
            var_name?: string | null;
            /** Source Line */
            source_line?: number | null;
            /** Source Text */
            source_text?: string | null;
            /** Args */
            args?: {
                [key: string]: string;
            };
            profile: components["schemas"]["FrameProfile"];
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Rows In */
            rows_in?: number | null;
            schema_change?: components["schemas"]["SchemaChange"] | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Examples */
            examples?: components["schemas"]["RowExamples"][];
        };
        /** NodeDiff */
        NodeDiff: {
            /** A */
            a: string;
            /** B */
            b: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "same" | "ancestor" | "descendant" | "unrelated";
            /** Path */
            path?: components["schemas"]["PathStep"][];
            /** Rows A */
            rows_a: number;
            /** Rows B */
            rows_b: number;
            /** Cols A */
            cols_a: number;
            /** Cols B */
            cols_b: number;
            /** Memory A */
            memory_a: number;
            /** Memory B */
            memory_b: number;
            /** Index A */
            index_a: string[];
            /** Index B */
            index_b: string[];
            /** Columns */
            columns: components["schemas"]["ColumnDiff"][];
        };
        /** PathStep */
        PathStep: {
            /** Node Id */
            node_id: string;
            /** Op */
            op: string;
            /** Label */
            label: string;
            /** Var Name */
            var_name?: string | null;
            /** Rows */
            rows: number;
        };
        /**
         * RowExamples
         * @description A few concrete rows illustrating what an operation lost, duplicated or nulled.
         */
        RowExamples: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "dropped" | "unmatched_left" | "unmatched_right" | "duplicate_keys_left" | "duplicate_keys_right" | "null_keys_left" | "null_keys_right" | "nulls";
            /** Label */
            label: string;
            /** Total */
            total: number;
            /** Column */
            column?: string | null;
            /** Highlight */
            highlight?: string[];
            /** Columns */
            columns: string[];
            /** Index */
            index: unknown[];
            /** Rows */
            rows: unknown[][];
        };
        /** SchemaChange */
        SchemaChange: {
            /** Added */
            added?: string[];
            /** Removed */
            removed?: string[];
            /** Dtype Changed */
            dtype_changed?: {
                [key: string]: [
                    string,
                    string
                ];
            };
        };
        /** StoredTrace */
        StoredTrace: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Created At */
            created_at: string;
            /** N Nodes */
            n_nodes: number;
            /** N Findings */
            n_findings: number;
            /** Has Error */
            has_error: boolean;
            /** Code */
            code: string;
            result: components["schemas"]["TraceResult"];
        };
        /** TraceError */
        TraceError: {
            /** Type */
            type: string;
            /** Message */
            message: string;
            /** Line */
            line?: number | null;
            /** Traceback */
            traceback: string;
        };
        /** TraceRequest */
        TraceRequest: {
            /** Code */
            code: string;
            /**
             * Timeout S
             * @default 30
             */
            timeout_s: number;
        };
        /** TraceResult */
        TraceResult: {
            /** Nodes */
            nodes?: components["schemas"]["Node"][];
            /** Edges */
            edges?: components["schemas"]["Edge"][];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Hints */
            hints?: components["schemas"]["Hint"][];
            /** Checks */
            checks?: components["schemas"]["Check"][];
            /**
             * Checks Script
             * @default
             */
            checks_script: string;
            /**
             * Stdout
             * @default
             */
            stdout: string;
            error?: components["schemas"]["TraceError"] | null;
            /** Warnings */
            warnings?: string[];
        };
        /** TraceSummary */
        TraceSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Created At */
            created_at: string;
            /** N Nodes */
            n_nodes: number;
            /** N Findings */
            n_findings: number;
            /** Has Error */
            has_error: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
        };
    };
    examples_api_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Example"][];
                };
            };
        };
    };
    trace_api_trace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"][];
                };
            };
        };
    };
    upload_dataset_api_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_datasets__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_api_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traces_api_traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSummary"][];
                };
            };
        };
    };
    stored_trace_api_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
